@start cmd /c python manager.py --port 8980
@start cmd /c python philosopher.py --port 8981
@start cmd /c python philosopher.py --port 8982
@start cmd /c python philosopher.py --port 8983
@start cmd /c python philosopher.py --port 8984
@start cmd /c python philosopher.py --port 8985
@start cmd /c python philosopher.py --port 8986
@start cmd /c python philosopher.py --port 8987
@start cmd /c python philosopher.py --port 8988
@start cmd /c python philosopher.py --port 8989
@start cmd /c python philosopher.py --port 8990
@start cmd /c python philosopher.py --port 8991
@start cmd /c python philosopher.py --port 8992
@start cmd /c python philosopher.py --port 8993
@start cmd /c python philosopher.py --port 8994
@start cmd /c python philosopher.py --port 8995
@start cmd /c python philosopher.py --port 8996
@start cmd /c python philosopher.py --port 8997
@start cmd /c python philosopher.py --port 8998
@start cmd /c python philosopher.py --port 8999
@start cmd /c python philosopher.py --port 9000